vocabularies = {
    "Leisure": "Noun: 空閒，休閒",
    "Inquire": "Verb: 詢問，打聽",
    "Scarce": "Adjective: 難得的，罕見的",
    "Convincing": "Adjective: 有說服力的",
    "Contagious": "Adjective: （疾病）接觸性傳染的，（情感）具有感染力的",
    "Conquer": "Verb: 征服，克服，戰勝",
    "Reluctant": "Adjective: 勉強的，不情願的",
    "Intensify": "Verb: 強化，增強",
    "Favorably": "Adverb: 善意的，順利的",
    "Adopt": "Verb: 採納，領養",
    "Disregard": "Verb: 不理會，忽視",
    "Incentive": "Noun: 誘因，獎勵金，激勵",
    "Prospect": "Noun: 前景，展望",
    "Variety": "Noun: 多樣性，變化",
    "Improvise": "Verb: 即興創作，臨時應變",
    "Accompany": "Verb: 陪伴，伴隨",
    "Ancient": "Adjective: 古代的，古老的",
    "Exhibition": "Noun: 展覽，展示會",
    "Clarify": "Verb: 澄清，解釋",
    "Involved": "Adjective: 涉及的，有關的",
    "Vital": "Adjective: 重要的，必要的",
    "Though": "Conjunction: 雖然，儘管",
    "Indulgence": "Noun: 放縱，沉溺",
    "Despite": "Preposition: 儘管，不顧",
    "Marginal": "Adjective: 邊緣的，不重要的",
    "Approximate": "Adjective: 近似的，大概的",
    "Patron": "Noun: 贊助人，顧客",
    "Indicate": "Verb: 指示，顯示",
    "Attract": "Verb: 吸引，引起興趣",
    "Means": "Noun: 方法，手段",
    "Contemporary": "Adjective: 當代的，現代的",
    "Dedicate": "Verb: 致力，獻身",
    "Imperative": "Adjective: 迫切的，必要的",
    "Commission": "Noun: 委託，佣金",
    "Omit": "Verb: 省略，刪去",
    "Proficient": "Adjective: 熟練的，精通的",
    "Confidentiality": "Noun: 保密，機密性",
    "Dispute": "Noun: 爭端，爭議",
    "Carrier": "Noun: 運輸公司，攜帶者",
    "Customarily": "Adverb: 習慣上，通常",
    "Custom": "Noun: 習俗，慣例",
    "Customs": "Noun: 海關，關稅",
    "Plentiful": "Adjective: 豐富充足的",
    "Compromise": "Noun: 妥協，讓步；Verb: 妥協，讓步",
    "Collaborate": "Verb: 合作，協作",
    "Lucrative": "Adjective: 有利可圖的，賺錢的",
    "Disclose": "Verb: 揭露，透露",
    "Confident": "Adjective: 有信心的，自信的",
    "Attraction": "Noun: 吸引力，吸引人的事物",
    "Diverse": "Adjective: 多樣的，不同的",
    "Superb": "Adjective: 極好的，出色的",
    "Declare": "Verb: 宣佈，聲明",
    "Commodity": "Noun: 商品，日用品",
    "Acclaim": "Noun: 讚譽，歡呼；Verb: 讚揚，歡呼",
    "Quote": "Noun: 引述，引文；Verb: 引述，報價",
    "Perishable": "Adjective: 易腐爛的，易變質的",
    "Courier": "Noun: 快遞，信差",
    "Adequately": "Adverb: 充足地，足夠地",
    "Formerly": "Adverb: 以前，從前",
    "Correspondence": "Noun: 信件，通信",
    "Bulk": "Noun: 體積，容積；Adjective: 大批量的；Verb: 變大，使形成大塊",
    "Acquisition": "Noun: 獲得，收購",
    "Subject": "Noun: 主題，題目；Adjective: 受...影響的；Verb: 使隸屬於，使受制於",
    "Seek": "Verb: 尋求，追求",
    "Measure": "Noun: 措施，方法；Verb: 測量，衡量",
    "Bargain": "Noun: 交易，協議；Verb: 討價還價，議價",
    "Beset": "Verb: 困擾，煩擾",
    "Encourage": "Verb: 鼓勵，激勵",
    "Reputation": "Noun: 名聲，聲譽",
    "Premises": "Noun: 房屋，場所",
    "Clerk": "Noun: 職員，店員",
    "Convey": "Verb: 傳達，運輸",
    "Cruise": "Verb: 巡航，航遊",
    "Fascinating": "Adjective: 迷人的，有吸引力的",
    "Luxurious": "Adjective: 奢華的，豪華的",
    "Complimentary": "Adjective: 免費贈送的，讚揚的",
    "Postage": "Noun: 郵資，郵費",
    "Carousel": "Noun: 旋轉式行李輸送帶，圓盤式搭乘設施",
    "Severely": "Adverb: 嚴重地，嚴厲地",
    "Thoroughly": "Adverb: 徹底地，完全地",
    "Drastically": "Adverb: 激烈地，徹底地",
    "Mandate": "Noun: 命令，指令；Verb: 授權，委託",
    "Adhere": "Verb: 遵守，堅持",
    "Refrain": "Verb: 克制，節制",
    "Constant": "Adjective: 持續的，不斷的；Noun: 常數",
    "Conduct": "Noun: 行為，舉止；Verb: 實施，進行",
    "Imply": "Verb: 暗示，意味著",
    "Expedite": "Verb: 促進，加速",
    "Substantially": "Adverb: 大大地，相當多地",
    "Significantly": "Adverb: 顯著地，大大地",
    "Anticipate": "Verb: 預期，期望",
    "Proceeds": "Noun: 收入",
    "Considerably": "Adverb: 相當，相當多地",
    "Prompt": "Adjective: 即時的，迅速的",
}
